'use client';
import { useRef, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { Assumption, AssumptionValue, ExtractionResponse, ExtractionService, extractionService, samples, dataIssues, laptopCorrection } from '@/lib/extraction';
import { buildCorrectionRequest } from '@/lib/corrections';
import { calculatorService } from '@/lib/calculator';
const labels:Record<string,string>={monthly_income:'Monthly income',monthly_expenses:'Monthly expenses',monthly_surplus:'Monthly surplus',current_savings:'Current savings',goal_amount:'Goal amount',goal_deadline:'Goal deadline',goal_description:'Goal description'};
const label=(v:string)=>labels[v] || v.replaceAll('_',' ');
const sourceLabels={stated:'You told us',inferred:'We inferred',missing:'Still missing'};
const config:Record<string,{min:number;max:number;step:number}>={monthly_income:{min:0,max:10000,step:50},monthly_expenses:{min:0,max:5000,step:25},current_savings:{min:0,max:20000,step:50},goal_amount:{min:0,max:10000,step:50},goal_deadline:{min:1,max:36,step:1}};
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
export function AssumptionRow({a,index,value,local,confirmed,stale,onEdit,onConfirm,onUnderlying,questionIndex,children}:{a:Assumption;index:number;value:AssumptionValue;local:boolean;confirmed:boolean;stale:boolean;onEdit:(v:AssumptionValue)=>void;onConfirm:()=>void;onUnderlying:()=>void;questionIndex:number;children?:ReactNode}) {
 const [editing,setEditing]=useState(false); const [sourceOpen,setSourceOpen]=useState(false); const [draft,setDraft]=useState(''); const [error,setError]=useState('');
 const numeric=typeof value==='number' || (value===null && (a.unit?.includes('$')||a.unit==='months'||a.unit==='%'));
 const c=config[a.variable]; const n=Number(draft); const derived=a.variable==='monthly_surplus';
 const subdued=(a.source==='stated'||confirmed)&&!stale;
 const save=()=>{if(numeric && (draft.trim()===''||!Number.isFinite(n))) {setError('Enter a valid number.');return;} onEdit(numeric?n:draft);setEditing(false);setError('');};
 return <article title={a.source_detail} data-source={a.source} className={`assumption ${subdued ? 'subdued' : a.source==='inferred' ? 'to-confirm' : 'needs-information'} ${editing ? 'is-editing' : ''}`} id={`assumption-${index}`}>
  <div className="row-main"><div className="row-label"><strong>{label(a.variable)}</strong><span className="row-value">{stale?'Requires recalculation':value===null?<span className="muted">Not provided yet</span>:typeof value==='number'?(a.unit?.startsWith('$')?money(value):value.toLocaleString('en-US')):value}{!stale&&value!==null&&a.unit&&<small>{a.unit==='$/month'?' / month':a.unit==='$'?'':` ${a.unit}`}</small>}</span>  <div className="row-actions">{value!==null&&!stale&&<button className={confirmed?'confirmed-action':''} disabled={confirmed} onClick={onConfirm}>{confirmed?'Confirmed':'Looks right'}</button>}{derived?<button onClick={onUnderlying}>Edit</button>:value===null?<a href={questionIndex>=0?`#question-${questionIndex}`:'#correction'}>Add information ↗</a>:<button onClick={()=>{setDraft(String(value));setEditing(true);}}>Edit</button>}</div></div>
  <div className="tags">{a.source!=='stated'&&<span className={`badge ${a.source}`}>{sourceLabels[a.source]}</span>}{!subdued&&<button className="source-toggle" aria-expanded={sourceOpen} aria-controls={`source-${index}`} onClick={()=>setSourceOpen(!sourceOpen)}>Why this value? {sourceOpen?'−':'+'}</button>}{local&&<span className="annotation">Local edit</span>}</div>
</div>
  {sourceOpen&&!subdued&&<p className="source-detail" id={`source-${index}`}>{a.source_detail}</p>}
  {editing&&<div className="editor"><label>{label(a.variable)}<input aria-label={`Edit ${label(a.variable)}`} type={numeric?'number':/^\d{4}-\d{2}-\d{2}$/.test(String(value))?'date':'text'} step="any" value={draft} onChange={e=>setDraft(e.target.value)}/></label>{numeric&&c&&draft!==''&&Number.isFinite(n)&&<><input aria-label={`${label(a.variable)} slider`} type="range" min={Math.min(c.min,n)} max={Math.max(c.max,n)} step={c.step} value={n} onChange={e=>setDraft(e.target.value)}/><small>Range {Math.min(c.min,n)}–{Math.max(c.max,n)} · step {c.step}. Use the number field for precise values.</small></>}<div className="actions"><button className="primary small" onClick={save}>Save locally</button><button onClick={()=>{setEditing(false);setError('');}}>Cancel</button></div>{error&&<p role="alert">{error}</p>}</div>}
  {children}
 </article>;
}
export default function Workspace({service=extractionService}:{service?:ExtractionService}) {
 const [input,setInput]=useState(''); const [original,setOriginal]=useState(''); const [rawExtraction,setRaw]=useState<ExtractionResponse|null>(null);
 const [reviewState,setReview]=useState<Record<number,boolean>>({}); const [draftOverrides,setOverrides]=useState<Record<number,AssumptionValue>>({});
 const [questionAnswers,setAnswers]=useState<Record<number,string>>({}); const [savedAnswers,setSaved]=useState<Record<number,string>>({});
 const [expenseDirty,setExpenseDirty]=useState(false);
 const [scenarioDraft,setScenario]=useState({allocated:'',contribution:300}); const [preview,setPreview]=useState(false);
 const [correction,setCorrection]=useState(''); const [history,setHistory]=useState<{correction:string;extraction:ExtractionResponse}[]>([]);
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [status,setStatus]=useState(''); const [goalDraft,setGoal]=useState(''); const [goalEditing,setGoalEditing]=useState(false);
 const version=useRef(0); const revision=useRef(0);
 const context=()=>({user_message:original,reference_date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),timezone:'America/New_York'});
 const reset=()=>{version.current++;revision.current++;setRaw(null);setExpenseDirty(false);setInput('');setOriginal('');setBusy(false);setError('');setHistory([]);setOverrides({});setReview({});setAnswers({});setSaved({});setScenario({allocated:'',contribution:300});setPreview(false);setCorrection('');setStatus('');setGoal('');setGoalEditing(false);};
 async function extract(){if(busy)return;const v=++version.current;setBusy(true);setError('');setOriginal(input);try{const result=await service.extract({...context(),user_message:input});if(v!==version.current)return;setRaw(result);setStatus('Ready for your review');}catch(e){if(v===version.current)setError((e as Error).message);}finally{if(v===version.current)setBusy(false);}}
 const invalidate=()=>{revision.current++;setPreview(false);};
 const raw=rawExtraction; const value=(i:number)=>Object.hasOwn(draftOverrides,i)?draftOverrides[i]:raw!.assumptions[i].value;
 const changed=raw?.assumptions.some((a,i)=>Object.hasOwn(draftOverrides,i)&&['monthly_income','monthly_expenses'].includes(a.variable));
 const expenseCategories=['monthly_car_payment','monthly_student_loan_payment','current_rent','monthly_rent','monthly_food','monthly_utilities','monthly_expenses_rent','monthly_expenses_other','monthly_expenses_rent_utilities'];
 const categoryChanged=expenseDirty;
 const issues=raw?dataIssues(raw):[];
 const pending=raw?.assumptions.filter((a,i)=>a.source==='inferred'&&!reviewState[i]).length || 0;
 const unanswered=raw?.clarification_questions.filter((_,i)=>!savedAnswers[i]).length||0;
 const get=(name:string)=>{const i=raw?.assumptions.findIndex(a=>a.variable===name)??-1;return i<0?null:value(i);};
 const blockers:string[]=[];let result:ReturnType<typeof calculatorService.calculate>|null=null;
 const supported=raw?.assumptions.some(a=>a.variable==='goal_amount');
 if(raw&&supported){for(const name of ['monthly_income','monthly_expenses','goal_deadline','goal_amount','current_savings']){const i=raw.assumptions.findIndex(a=>a.variable===name);if(i<0||typeof value(i)!=='number')blockers.push(`Provide ${label(name).toLowerCase()}.`);else if(raw.assumptions[i].source==='inferred'&&!reviewState[i])blockers.push(`Confirm ${label(name).toLowerCase()}.`);}if(categoryChanged&&!raw.assumptions.some((a,i)=>a.variable==='monthly_expenses'&&Object.hasOwn(draftOverrides,i)&&reviewState[i]))blockers.push('Expense categories changed. Supply and review an updated expense total.');raw.clarification_questions.forEach((q,i)=>{if(['monthly_income','monthly_expenses','goal_deadline'].includes(q.target_variable)&&(!savedAnswers[i]||savedAnswers[i]!==questionAnswers[i]))blockers.push(`Answer the question about ${label(q.target_variable).toLowerCase()}.`);});if(scenarioDraft.allocated.trim()==='')blockers.push('Explicitly choose how much savings to allocate.');if(issues.length)blockers.push('Resolve response data issues before calculating.');
 if(!blockers.length)try{result=calculatorService.calculate({income:get('monthly_income') as number,expenses:get('monthly_expenses') as number,months:get('goal_deadline') as number,goal:get('goal_amount') as number,savings:get('current_savings') as number,allocated:Number(scenarioDraft.allocated),contribution:scenarioDraft.contribution});}catch(e){blockers.push((e as Error).message);}}
 async function apply(){if(!raw||busy)return;const request=buildCorrectionRequest(context(),raw,{goal:goalDraft,correction,overrides:draftOverrides,answers:savedAnswers});const content=request.user_correction;if(!content){setStatus('No corrections to apply.');return;}const v=++version.current;const r=revision.current;setBusy(true);setError('');try{const next=await service.correct(request);if(v!==version.current||r!==revision.current){setStatus('Review changed while saving. Response discarded; drafts retained.');return;}setHistory(h=>[...h,{correction:content,extraction:raw}]);setRaw(next);setExpenseDirty(false);setReview({});setOverrides({});setAnswers({});setSaved({});setCorrection('');setGoal('');setPreview(false);setStatus('Updated just now');}catch(e){if(v===version.current)setError((e as Error).message);}finally{if(v===version.current)setBusy(false);}}
 const renderQuestion=(q:ExtractionResponse['clarification_questions'][number],i:number)=><div className="question" id={`question-${i}`} key={i}><label htmlFor={`answer-${i}`}><span className="question-number">{i+1}</span>{q.question}</label><input id={`answer-${i}`} value={questionAnswers[i]||''} placeholder="Your answer…" onChange={e=>{setAnswers(s=>({...s,[i]:e.target.value}));invalidate();}}/><details><summary>Why it matters</summary><p>{q.why_it_matters}</p></details>{savedAnswers[i]&&<small className="annotation">Answer saved locally{savedAnswers[i]!==questionAnswers[i]?' · Unsaved changes':''}</small>}</div>;
 const inferredQuestion=(target:string)=>raw?.assumptions.some(a=>a.source==='inferred'&&a.variable===target);
 return <><header className="site-header"><Link className="brand" href="/" aria-label="Show Your Work home"><span className="sun">☀</span>Show Your Work</Link><div className="header-right"><span className="demo">Demo mode</span><button className="new-question" onClick={reset}>＋ New question</button></div></header>
 <main><div aria-live="polite" className="sr-only">{busy?'Reviewing your description':status}</div>
 {!raw&&!busy&&<section className="intro"><span className="eyebrow">A LITTLE CLARITY GOES A LONG WAY</span><h1>What’s on your mind?</h1><p>A trip, a new laptop, a fresh start.<br/>Let’s make the numbers a little less mysterious.</p><div className="input-card"><label htmlFor="description">Tell us what you’re working toward</label><textarea id="description" value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe your goal, the numbers you know, and anything you’re unsure about…"/><div className="input-footer"><span>Sample data. Your money stays yours.</span><button className="primary" disabled={!input.trim()} onClick={extract}>Continue <span>→</span></button></div></div><div className="sample-heading">TRY AN EXAMPLE</div><div className="samples">{samples.map(s=><button key={s.id} onClick={()=>{setInput(s.message);setError('');}}><span>{s.icon}</span>{s.title}<span>↗</span></button>)}</div><div className="principles"><span>◉ See every assumption</span><span>✎ Make it yours</span><span>↔ Explore the trade-offs</span></div></section>}
 {(raw||busy)&&<><div className="user-message"><div>{original}</div><span className="avatar">Y</span></div><div className="assistant-message"><span className="assistant-avatar">☀</span><div>{busy?'Reviewing your description…':'Let’s start with what we know. You can check and change every assumption.'}</div></div></>}
 {busy&&!raw&&<section className="working-card skeleton" aria-label="Reviewing your description"><div/><div/><div/></section>}
 {error&&<div className="error" role="alert">{error}{!raw&&<button disabled={busy} onClick={extract}>Retry</button>}</div>}
 {raw&&<><div className="plan-pill">◇ Working card · Review open</div><section className="working-card"><div className="card-header"><div><span className="eyebrow">YOUR WORKING CARD</span><h2>Here’s what we understood</h2><p>{raw.goal_summary}</p>{goalDraft&&<p className="annotation">Local edit · {goalDraft}</p>}</div><button onClick={()=>setGoalEditing(!goalEditing)}>Edit goal</button></div>
 {goalEditing&&<div className="editor"><label>Goal correction<textarea value={goalDraft} onChange={e=>{setGoal(e.target.value);invalidate();}}/></label><button onClick={()=>setGoalEditing(false)}>Keep draft</button></div>}
 <div className="review-summary"><span>✧ A good plan starts with good assumptions.</span><div><a href="#inferred">{pending} to confirm</a><a href="#questions">{unanswered} questions</a></div></div>
 {issues.length>0&&<div className="error">{issues.map((x,i)=><p key={i}>{x}</p>)}</div>}
 {raw.assumptions.length===0&&<p>No assumptions returned. Add a correction below.</p>}
 {(['stated','inferred','missing'] as const).map(source=>{const rows=raw.assumptions.map((a,i)=>({a,i})).filter(({a})=>a.source===source);const Wrapper='div';return rows.length>0&&<Wrapper key={source} className="source-section"><section className="source-group" id={source} key={source}><div className="group-heading"><h3>{sourceLabels[source]}</h3><span>{rows.length} {rows.length===1?'assumption':'assumptions'}</span></div>{rows.map(({a,i})=><AssumptionRow key={i} index={i} a={a} value={value(i)} local={Object.hasOwn(draftOverrides,i)} confirmed={!!reviewState[i]} stale={(a.variable==='monthly_surplus'&&!!(changed||categoryChanged))||(a.variable==='monthly_expenses'&&!!categoryChanged&&!Object.hasOwn(draftOverrides,i))} questionIndex={raw.clarification_questions.findIndex(q=>q.target_variable===a.variable)} onUnderlying={()=>document.getElementById(`assumption-${raw.assumptions.findIndex(x=>x.variable==='monthly_income')}`)?.scrollIntoView({behavior:'smooth'})} onConfirm={()=>{setReview(s=>({...s,[i]:true}));invalidate();}} onEdit={v=>{setOverrides(s=>({...s,[i]:v}));if(expenseCategories.includes(a.variable))setExpenseDirty(true);if(a.variable==='monthly_expenses')setExpenseDirty(false);setReview(s=>{const next={...s,[i]:false};if(['monthly_income','monthly_expenses',...expenseCategories].includes(a.variable))raw.assumptions.forEach((other,j)=>{if(other.variable==='monthly_surplus'||(expenseCategories.includes(a.variable)&&other.variable==='monthly_expenses'))next[j]=false;});return next;});invalidate();}}>{a.source==='inferred'&&raw.assumptions.findIndex(x=>x.source==='inferred'&&x.variable===a.variable)===i&&raw.clarification_questions.map((q,qi)=>q.target_variable===a.variable?renderQuestion(q,qi):null)}</AssumptionRow>)}</section></Wrapper>;})}
 <section className="questions" id="questions"><div className="group-heading"><h3>Questions for you</h3><span>A little more context</span></div>{raw.clarification_questions.length===0?<p>No clarification questions returned.</p>:raw.clarification_questions.map((q,i)=>inferredQuestion(q.target_variable)?null:renderQuestion(q,i))}{raw.clarification_questions.length>0&&<button onClick={()=>{setSaved({...questionAnswers});setStatus('Answers saved locally. Original questions remain for review.');invalidate();}}>Save answers</button>}</section>
 <aside className="extraction-note"><span>ⓘ</span><div><strong>Extraction note</strong><p>{raw.confidence_note}</p></div></aside>
 <section className="scenario"><div className="group-heading"><h3>Explore the numbers</h3><span>STEP 02</span></div>{!supported?<p>Calculator not connected for this scenario.</p>:<><p className="muted">Local example calculation · Choose your allocation, then preview a savings scenario.</p><label>Savings allocated to this goal ($)<input type="number" step="any" value={scenarioDraft.allocated} placeholder="Choose an amount" onChange={e=>{setScenario(s=>({...s,allocated:e.target.value}));setPreview(false);}}/></label>{blockers.length>0&&<ul className="blockers">{blockers.map((b,i)=><li key={i}>{b}</li>)}</ul>}<button disabled={blockers.length>0} onClick={()=>setPreview(true)}>Preview example calculation ↗</button>{preview&&!result&&<p role="alert">Adjust the scenario inputs to continue.</p>}{preview&&<div className="scenario-controls"><label>Monthly contribution <input type="number" step="any" min="0" value={scenarioDraft.contribution} onChange={e=>setScenario(s=>({...s,contribution:Number(e.target.value)}))}/></label><input aria-label="Monthly contribution slider" type="range" min="0" max={Math.max(1000,scenarioDraft.contribution)} step="10" value={scenarioDraft.contribution} onChange={e=>setScenario(s=>({...s,contribution:Number(e.target.value)}))}/><small>Range $0–${Math.max(1000,scenarioDraft.contribution)} · step $10</small></div>}{preview&&result&&<div className="preview"><div className="results"><div><small>Goal amount</small><strong>{money(get('goal_amount') as number)}</strong></div><div><small>Projected at deadline</small><strong>{money(result.projected)}</strong></div><div><small>Remaining gap</small><strong>{money(result.gap)}</strong></div></div><p>{result.exceeds?'Cash flow exceeds available amount':`${money(result.remaining)} remaining each month`}</p><details><summary>Calculation details</summary><p>{money(Number(scenarioDraft.allocated))} + {money(scenarioDraft.contribution)} × {String(get('goal_deadline'))} months = {money(result.projected)}</p><p>Gap = max(0, {money(get('goal_amount') as number)} − {money(result.projected)}) = {money(result.gap)}</p><p>Monthly remaining = {money(get('monthly_income') as number)} − {money(get('monthly_expenses') as number)} − {money(scenarioDraft.contribution)} = {money(result.remaining)}</p><p>Conditions: constant income and expenses; no interest, unlisted costs, or competing goals. Only the explicitly allocated savings are used. Expense categories are not added to the total.</p></details></div>}</>}</section>
 <footer className="card-footer"><span>{status}{Object.keys(draftOverrides).length>0&&' · Pending local corrections'}</span><button className="primary" disabled={busy} onClick={apply}>{busy?'Saving…':'Apply corrections →'}</button></footer></section>
 {original===samples[1].message&&<button className="demo-correction" onClick={()=>{setCorrection(laptopCorrection);setStatus('Predefined demo correction selected. Apply corrections to update the card.');invalidate();}}>Try a demo correction: income, expenses & deadline</button>}{history.length>0&&<details className="history"><summary>Correction history ({history.length})</summary>{history.map((h,i)=><details key={i}><summary>{h.correction}</summary><pre>{JSON.stringify(h.extraction,null,2)}</pre></details>)}</details>}
 <div className="composer" id="correction"><label className="sr-only" htmlFor="correction-input">Add a correction</label><span>＋</span><textarea id="correction-input" value={correction} onChange={e=>{setCorrection(e.target.value);invalidate();}} placeholder="Add a correction or another condition…"/><button className="send" aria-label="Apply correction" disabled={busy||!correction.trim()} onClick={apply}>↑</button></div><p className="demo-footnote">Demo mode · Corrections stay as drafts until the extraction service is connected.</p></>}
 </main><footer className="site-footer">SHOW YOUR WORK <span>Less guessing. More understanding.</span></footer></>;
}
