import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
import Module, {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const require = createRequire(import.meta.url);
const cache = new Map();
function load(file) {
 file=path.resolve(file);if(cache.has(file)) return cache.get(file).exports;
 const m = new Module(file);m.filename=file;m.paths=require.resolve.paths('typescript');cache.set(file,m);
 const normalRequire=m.require.bind(m);
 m.require=id=>id.startsWith('@/lib/')?load(`lib/${id.slice(6)}.ts`):normalRequire(id);
 m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
 return m.exports;
}
const e=load('lib/extraction.ts');
const {buildCorrectionRequest}=load('lib/corrections.ts');
const {AssumptionRow}=load('components/workspace.tsx');
const notebook=JSON.parse(fs.readFileSync('../show_your_work_extraction.ipynb','utf8'));
const rawText=notebook.cells[16].outputs.map(o=>(o.text??o.data?.['text/plain']??[]).join('')).join('');
const actual=JSON.parse(rawText.slice(rawText.indexOf('{')));
const provenance=JSON.parse(fs.readFileSync('lib/fixtures/grace-notebook-case3-provenance.json','utf8'));
const context={user_message:provenance.user_message,reference_date:'2026-10-07',timezone:'America/New_York'};
const rendered=(a,extra={})=>renderToStaticMarkup(React.createElement(AssumptionRow,{a,index:0,value:a.value,local:false,confirmed:false,stale:false,questionIndex:-1,onEdit(){},onConfirm(){},onUnderlying(){},...extra}));
const row=(value,source='stated',unit='')=>({variable:'unfamiliar_variable',value,source,unit,source_detail:'Original provenance'});
const loaded=await new e.MockExtractionService().extract(context);
assert.deepEqual(loaded,actual,'normal service loads saved notebook JSON unchanged');
assert.equal(actual.assumptions.length,9);
assert.equal(loaded.assumptions[8].unit,null);
for(const unit of [undefined,42,[],{}])assert.throws(()=>e.validateExtraction({...actual,assumptions:[{...actual.assumptions[0],unit}]}),/format error/);
assert.equal(actual.clarification_questions.length,3);
assert.deepEqual(e.validateExtraction({...actual,additional_metadata:{retained:true}}).additional_metadata,{retained:true});
for(const a of actual.assumptions){const html=rendered(a);assert.match(html,new RegExp(`data-source="${a.source}"`));}
assert.match(rendered(actual.assumptions[1]),/monthly expenses rent/);
assert.match(rendered(actual.assumptions[8]),/Europe trip with friends/);
assert.match(rendered(row(null,'missing','$/month')),/Not provided yet/);
assert.doesNotMatch(rendered(row(null,'missing','$/month')),/\$0/);
assert.match(rendered(row(0,'stated','$')),/\$0\.00/);
assert.match(rendered(row(-50,'inferred','$/month')),/-\$50\.00/);
assert.match(rendered(row('2027-02-01','stated','date')),/2027-02-01/);
assert.match(rendered(row(6,'stated','%')),/>6<.* %/);
assert.match(rendered(actual.assumptions[3],{confirmed:true}),/data-source="inferred"/);
assert.match(rendered(actual.assumptions[3],{confirmed:true}),/>Confirmed</);
assert.match(rendered(actual.assumptions[0],{value:1800,local:true}),/Local edit/);
assert.equal(actual.assumptions[0].value,2000,'rendering local edits leaves original untouched');
assert.deepEqual(e.validateExtraction({...actual,clarification_questions:[]}).clarification_questions,[]);
const absent={target_variable:'savings_allocated_to_goal',question:'How much would you allocate?',why_it_matters:'Keep total savings separate.'};
const extended={...actual,clarification_questions:[...actual.clarification_questions,absent]};
assert.equal(e.validateExtraction(extended).clarification_questions.at(-1).target_variable,'savings_allocated_to_goal');
for(const source of [['stated'],null,{},42,'unknown']) assert.throws(()=>e.validateExtraction({...actual,assumptions:[{...actual.assumptions[0],source}]}),/format error/);
for(const value of [undefined,true,{},NaN,Infinity])assert.throws(()=>e.validateExtraction({...actual,assumptions:[{...actual.assumptions[0],value}]}),/format error/);
const duplicate={...actual,assumptions:[...actual.assumptions,actual.assumptions[0]]};assert.equal(e.validateExtraction(duplicate).assumptions.length,10);assert.match(e.dataIssues(duplicate).join(' '),/Duplicate/);
assert.match(e.dataIssues({...actual,assumptions:[row(0,'missing')]}).join(' '),/Inconsistent/);
const before=JSON.stringify(extended);
const request=buildCorrectionRequest(context,extended,{goal:'',correction:'Keep emergency savings untouched.',overrides:{0:1800},answers:{1:'$500',3:'$400'}});
assert.equal(request.user_message,provenance.user_message);
assert.strictEqual(request.previous_extraction,extended);
assert.equal(request.reference_date,'2026-10-07');assert.equal(request.timezone,'America/New_York');
assert.match(request.user_correction,/monthly_income: 1800/);
assert.match(request.user_correction,/How much of that are you comfortable allocating.*Answer: \$500/);
assert.match(request.user_correction,/How much would you allocate\? Answer: \$400/);
assert.equal(JSON.stringify(extended),before);
assert.equal(request.previous_extraction.assumptions.find(a=>a.variable==='current_savings').value,1200);
// Exercise the real HTTP adapter against a captured response, without claiming a live Python backend.
const savedFetch=globalThis.fetch;const calls=[];
try{
 globalThis.fetch=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return new Response(JSON.stringify(actual),{status:200,headers:{'Content-Type':'application/json'}});};
 const http=new e.HttpExtractionService('http://replay.invalid');
 assert.deepEqual(await http.extract(context),actual);assert.deepEqual(await http.correct(request),actual);
 assert.equal(calls[0].url,'http://replay.invalid/api/extract');assert.deepEqual(calls[0].body,context);
 assert.equal(calls[1].url,'http://replay.invalid/api/correct');assert.deepEqual(calls[1].body,request);
 globalThis.fetch=async()=>new Response(JSON.stringify({error:{code:'EXTRACTION_FAILED',message:'Backend unavailable'}}),{status:503});
 await assert.rejects(http.extract(context),/Backend unavailable/);
 globalThis.fetch=async()=>new Response(JSON.stringify({error:{message:'Wrong success shape'}}),{status:200});
 await assert.rejects(http.extract(context),/format error/);
}finally{globalThis.fetch=savedFetch;}
const incomeHtml=rendered({...actual.assumptions[0],source:'inferred',source_detail:'Annual salary divided by twelve; tax status unknown.'});
assert.doesNotMatch(incomeHtml,/after.tax/i);assert.match(incomeHtml,/Monthly income/);
console.log('PASS: actual notebook replay, dynamic row rendering, all source/value cases, immutable edits and provenance, absent question targets, exact correction context, HTTP adapter response/error contracts');
